# Generated by Django 4.2.1 on 2023-06-23 06:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, unique=True, verbose_name='Full name')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Phone')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='Email')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('delete_date', models.DateTimeField(blank=True, null=True, verbose_name='Delete date')),
            ],
            options={
                'verbose_name': 'Agent',
                'verbose_name_plural': 'Agents',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Project name')),
                ('budget_type', models.CharField(blank=True, choices=[('variable', 'Variable'), ('fixed', 'Fixed')], max_length=255, null=True, verbose_name='Budget type')),
                ('budget_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Budget amount')),
                ('expenses_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Expenses amount')),
                ('agent_commission_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed')], default='percentage', max_length=255, verbose_name='Agent commission type')),
                ('agent_commission', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Agent commission')),
                ('manager_commission', models.DecimalField(decimal_places=2, default=5, max_digits=10, verbose_name='Manager commission (%)')),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Revenue')),
                ('profit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Profit')),
                ('total_labor', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Total labor')),
                ('start_date', models.DateField(verbose_name='Start date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('delete_date', models.DateTimeField(blank=True, null=True, verbose_name='Delete date')),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='projects.agent', verbose_name='Agent')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.client', verbose_name='Client')),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='services.service', verbose_name='Service')),
                ('service_details', models.ManyToManyField(blank=True, to='services.service', verbose_name='Service details')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='SystemReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange', models.CharField(max_length=255, verbose_name='Exchange')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Amount')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Comment')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted at')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='system_rewards', to='projects.project', verbose_name='Project')),
            ],
            options={
                'verbose_name': 'System reward',
                'verbose_name_plural': 'System rewards',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Labor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.PositiveIntegerField(default=0, verbose_name='Hours')),
                ('minutes', models.PositiveIntegerField(default=0, verbose_name='Minutes')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Amount')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Comment')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('delete_date', models.DateTimeField(blank=True, null=True, verbose_name='Delete date')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='labors', to=settings.AUTH_USER_MODEL, verbose_name='Employee')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labors', to='projects.project', verbose_name='Project')),
            ],
            options={
                'verbose_name': 'Labor',
                'verbose_name_plural': 'Labors',
                'ordering': ['-id'],
            },
        ),
    ]
