# Generated by Django 4.2.1 on 2023-06-23 06:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=255, unique=True, verbose_name='Invoice number')),
                ('legal_person', models.CharField(blank=True, choices=[('RUNIT', 'ООО "РУНИТА"'), ('RA_RUNIT', 'ООО "РА РУНИТА"'), ('Uvarova', 'ИП Уварова')], db_index=True, max_length=255, null=True, verbose_name='Legal person (Our)')),
                ('payment_purpose', models.TextField(verbose_name='Payment purpose')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount')),
                ('billing_date', models.DateField(default=django.utils.timezone.now, verbose_name='Billing date')),
                ('paid_date', models.DateField(blank=True, null=True, verbose_name='Paid date')),
                ('close_date', models.DateField(blank=True, null=True, verbose_name='Close date')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Comment')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Updated at')),
                ('deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('deleted_comment', models.TextField(blank=True, verbose_name='Deleted comment')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='projects.project', verbose_name='Project')),
            ],
            options={
                'verbose_name': 'Client invoice (Summary)',
                'verbose_name_plural': 'Client invoices (Summary)',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ProjectExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_market', models.CharField(blank=True, max_length=255, null=True, verbose_name='Stock market')),
                ('month_request', models.DateField(blank=True, null=True, verbose_name='Request month')),
                ('budget_request', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Budget request')),
                ('spent', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Spent')),
                ('commission', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Commission')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Amount')),
                ('project_comment', models.TextField(blank=True, null=True, verbose_name='Comment to project')),
                ('expense_comment', models.TextField(blank=True, null=True, verbose_name='Comment to expense')),
                ('paid_date', models.DateField(blank=True, null=True, verbose_name='Paid date')),
                ('deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('deleted_comment', models.TextField(blank=True, verbose_name='Deleted comment')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Updated at')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='projects.project', verbose_name='Project')),
            ],
            options={
                'verbose_name': 'Project expense',
                'verbose_name_plural': 'Project expenses',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ManagerBonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_invoice', models.ManyToManyField(blank=True, related_name='bonuses', to='payments.clientinvoice', verbose_name='Client invoice')),
                ('manager', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bonus', to=settings.AUTH_USER_MODEL, verbose_name='Manager')),
            ],
            options={
                'verbose_name': 'Manager bonus',
                'verbose_name_plural': 'Manager bonuses',
                'ordering': ['-id'],
            },
        ),
    ]
